# Load vars
from lib.config.Main_Configs import Product_Name

# Register commands
Help_Commands = {
    # User
    'clear': f"Clear page.",
    '?': f"Show help page.",
    'help': f"Alias to `?`.",
    'select': f"Select operating device/devices.",
    'unselect': f"Unselect operating device/devices.",
    'list-selected': f"Show list of selected devices.",
    # ADB
    'devices': f"Show all connected devices (Remote or Cable)",
    'device_info': f"Show device(s) information.",
    'wlan_IP': f"Show wlan IP of device(s).",
    'tcp_IP [Port]': f"Convert LAN ADB device to remote ADB.",
    'connect [IP | IP:Port]': f"Connect to remote device(s) with IP.",
    'disconnect': f"Disconnect from remote device(s) with IP.",
    'wifi [off | on]': f"Turn on/off device(s) Wi-Fi. (Note: Will lost remote device(s))",
    'list_apps': f"Show list of installed apps.",
    'is_rooted': f"Check device(s) is rooted or not.",
    'command [command]': f"Run OS commands on device(s).",
    'install [APK path]': f"Install an APK on device(s).",
    'install_URL [APK URL]': f"Install an APK on device(s) from a URL.",
    'uninstall [package name]': f"Uninstall an application. (Danger: Lost data)",
    'open [package name]': f"Open an application.",
    'open [package name] [activity name]': f"Open activity of an application.",
    'close [package name]': f"Close an application.",
    'clear_data [package name]': f"Do clear data on an application. (Danger: Lost data)",
    'app_info [package name]': f"How information of application.",
    'shutdown': f"Shutdown & disconnect device(s). (Device(s) will be disconnect)",
    'reboot': f"Reboot (Restart) device(s). (Note: Will lost remote device(s))",
    'kill_server': f"Kill ADB server on {Product_Name} (All of devices will be lost)",
    'download [file path on device]': f"Download/Transfer file from device(s).",
    'upload [file path on hacker PC]': f"Download/Transfer file from {Product_Name} to device",
    'ls [path]': f"Show list of files/directories on the path.",
    'airplane [off | on]': f"Turn on/off airplane mode. (Note: Will lost remote device(s))",
    'battery': f"How battery level and charge information.",
    'netstat': f"Get full network connections list.",
    'volume [up | down]': f"Increase/decrease media volume level",
    'screen_status': f"Check status screen of device(s).",
    'mute-unmute': f"Mute/Unmute media volume.",
    'run_keycode [keycode numbers, ...]': f"Run a ADB keycode on device(s).",
    'browser [URL]': f"Open a URL in the default browser.",
    'screen [on | off]': f"Change status of device(s) screen.",
    'screen-lock': f"Lock device.",
    'screenshot [PNG path]': f"Take screenshot from devices.",
    'ps': f"Get list of all client process.",
    'contacts': f"Get list of contacts.",
    'sms': f"Get list of SMSs.",
    'type [Text]': f"Type a text on device."
}

Known_Commands = [
    'clear',
    '?',
    'help',
    'select',
    'unselect',
    'list-selected',
    'devices',
    'device_info',
    'wlan_IP',
    'tcp_IP',
    'connect',
    'disconnect',
    'wifi',
    'list_apps',
    'is_rooted',
    'command',
    'install',
    'install_URL',
    'uninstall',
    'open',
    'close',
    'clear_data',
    'app_info',
    'shutdown',
    'reboot',
    'kill_server',
    'download',
    'upload',
    'ls',
    'airplane',
    'battery',
    'netstat',
    'volume',
    'screen_status',
    'mute-unmute',
    'run_keycode',
    'browser',
    'screen',
    'screen-lock',
    'screenshot',
    'ps',
    'contacts',
    'sms',
    'type'
]
