Critical = 1  # exit with code 1
High = 2  # can't run but don't exit
Exclamation = 2  # !
Confirm = 3  #
Question = 3  # ?
Failed_Job = 4  # run but failed job
Minus = 4  # -
Alert = 5  # just show alert
Plus = 5  # +
Info = 6  # log a information
Star = 6  # *
NoStyle = None  # Don't style text
